internal static class JournalEndpoints
{
    internal static void Map(WebApplication app)
    {
        EdgeTransport.MapProxy(app, "/api/app/quick-observations", "journal", "/internal/quick-observations", [HttpMethods.Post]).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/market-observations", "journal", "/internal/market-observations", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/market-observations/{id:guid}", "journal", "/internal/market-observations/{id}", [HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/market-observations/today", "journal", "/internal/market-observations/today", [HttpMethods.Get]).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/observation-updates/{id:guid}", "journal", "/internal/observation-updates/{id}", [HttpMethods.Put, HttpMethods.Delete]).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/observation-updates/{updateId:guid}/expectations", "journal", "/internal/observation-updates/{updateId}/expectations", [HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/expectations", "journal", "/internal/expectations", [HttpMethods.Get]).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/expectations/{id:guid}", "journal", "/internal/expectations/{id}", [HttpMethods.Get, HttpMethods.Put, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/expectations/{id:guid}/invalidate", "journal", "/internal/expectations/{id}/invalidate", [HttpMethods.Post]).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/expectations/{id:guid}/review", "journal", "/internal/expectations/{id}/review", [HttpMethods.Get, HttpMethods.Put, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/expectations/{id:guid}/review-context", "journal", "/internal/expectations/{id}/review-context", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/reasoning-labels", "journal", "/internal/reasoning-labels", [HttpMethods.Get, HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/reasoning-labels/{id:guid}", "journal", "/internal/reasoning-labels/{id}", [HttpMethods.Put, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/observation-updates/{updateId:guid}/action-decisions", "journal", "/internal/observation-updates/{updateId}/action-decisions", [HttpMethods.Get, HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/action-decisions/{id:guid}", "journal", "/internal/action-decisions/{id}", [HttpMethods.Get, HttpMethods.Put, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/action-decisions/{decisionId:guid}/trades", "journal", "/internal/action-decisions/{decisionId}/trades", [HttpMethods.Get, HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/action-decisions/{decisionId:guid}/trades/{id:guid}", "journal", "/internal/action-decisions/{decisionId}/trades/{id}", [HttpMethods.Put, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/watchlist", "journal", "/internal/watchlist", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/watchlist/{instrumentId:guid}", "journal", "/internal/watchlist/{instrumentId}", [HttpMethods.Post, HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/watchlist/{instrumentId:guid}/note", "journal", "/internal/watchlist/{instrumentId}/note", [HttpMethods.Put], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/pattern-review", "journal", "/internal/pattern-review", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/confirmed-patterns", "journal", "/internal/confirmed-patterns", [HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/confirmed-patterns/{id:guid}", "journal", "/internal/confirmed-patterns/{id}", [HttpMethods.Delete], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/comparison", "journal", "/internal/comparison", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/discipline-principles", "journal", "/internal/discipline-principles", [HttpMethods.Get, HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/discipline-principles/today", "journal", "/internal/discipline-principles/today", [HttpMethods.Get], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/discipline-principles/{id:guid}", "journal", "/internal/discipline-principles/{id}", [HttpMethods.Put], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
        EdgeTransport.MapProxy(app, "/api/app/discipline-principles/{id:guid}/select", "journal", "/internal/discipline-principles/{id}/select", [HttpMethods.Post], preserveErrorBody: true).RequireAuthorization(TradeDiary.Authorization.TradeDiaryPolicies.JournalAccess);
    }
}
