apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: micro-cockpit
type: Opaque
stringData:
  LOCAL_REGISTRATION_KEY: "j5qtH1iI4rBBHVPzbW6jHlTz3Nwc13bA"
  INTERNAL_SERVICE_KEY: "EiO1Dihtkcm7MTbEnnuWJqTlWhOBVKy4"
