apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: identity-keys
  namespace: micro-cockpit
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 100Mi
