using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Npgsql;

var builder=WebApplication.CreateBuilder(args);
builder.Services.AddSingleton(_=>NpgsqlDataSource.Create(builder.Configuration.GetConnectionString("Content")??"Host=localhost;Port=5433;Database=trade_diary;Username=trade_diary;Password=local_only"));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>{o.MapInboundClaims=false;o.MetadataAddress=builder.Configuration["Auth:MetadataAddress"]??"http://127.0.0.1:5100/.well-known/openid-configuration";o.RequireHttpsMetadata=false;o.Audience="trade-diary-services";});
builder.Services.AddAuthorization(o=>o.FallbackPolicy=new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build());
var app=builder.Build();app.UseAuthentication();app.UseAuthorization();
app.MapGet("/health/live",()=>Results.Ok(new{status="healthy"})).AllowAnonymous();app.MapGet("/health/ready",async(NpgsqlDataSource db)=>{try{await db.OpenConnectionAsync();return Results.Ok(new{status="ready"});}catch{return Results.Json(new{status="not_ready"},statusCode:503);}}).AllowAnonymous();app.MapGet("/version",()=>Results.Ok(new{service="content-service",version="0.1.0"})).AllowAnonymous();
app.MapGet("/internal/posts",async(NpgsqlDataSource db)=>{await using var c=db.CreateCommand("SELECT id,slug,title,body,published_at FROM content.posts WHERE status='published' ORDER BY published_at DESC");await using var r=await c.ExecuteReaderAsync();var items=new List<object>();while(await r.ReadAsync())items.Add(new{id=r.GetGuid(0),slug=r.GetString(1),title=r.GetString(2),body=r.GetString(3),publishedAt=r.GetDateTime(4)});return Results.Ok(new{items});}).AllowAnonymous();
app.MapGet("/internal/posts/{slug}",async(string slug,NpgsqlDataSource db)=>{await using var c=db.CreateCommand("SELECT id,slug,title,body,published_at FROM content.posts WHERE slug=$1 AND status='published'");c.Parameters.AddWithValue(slug);await using var r=await c.ExecuteReaderAsync();return await r.ReadAsync()?Results.Ok(new{id=r.GetGuid(0),slug=r.GetString(1),title=r.GetString(2),body=r.GetString(3),publishedAt=r.GetDateTime(4)}):Results.NotFound();}).AllowAnonymous();
app.MapPost("/internal/admin/posts",async(PostWrite x,HttpRequest req,NpgsqlDataSource db)=>{
  if(!Admin(req,out var user))return Results.NotFound();if(string.IsNullOrWhiteSpace(x.Title)||string.IsNullOrWhiteSpace(x.Slug))return Results.BadRequest(new{error="title_and_slug_required"});var id=Guid.NewGuid();await using var c=db.CreateCommand("INSERT INTO content.posts(id,author_user_id,slug,title,body,status,published_at) VALUES($1,$2,$3,$4,$5,$6,CASE WHEN $6='published' THEN now() END)");c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(user);c.Parameters.AddWithValue(x.Slug.Trim().ToLowerInvariant());c.Parameters.AddWithValue(x.Title.Trim());c.Parameters.AddWithValue(x.Body??"");c.Parameters.AddWithValue(x.Status);try{await c.ExecuteNonQueryAsync();return Results.Created($"/internal/admin/posts/{id}",new{id});}catch(PostgresException e)when(e.SqlState==PostgresErrorCodes.UniqueViolation){return Results.Conflict(new{error="slug_exists"});}
});
app.MapPut("/internal/admin/posts/{id:guid}",async(Guid id,PostWrite x,HttpRequest req,NpgsqlDataSource db)=>{if(!Admin(req,out var user))return Results.NotFound();await using var c=db.CreateCommand("UPDATE content.posts SET slug=$3,title=$4,body=$5,status=$6,published_at=CASE WHEN $6='published' THEN coalesce(published_at,now()) ELSE published_at END,updated_at=now() WHERE id=$1 AND author_user_id=$2");c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(user);c.Parameters.AddWithValue(x.Slug.Trim().ToLowerInvariant());c.Parameters.AddWithValue(x.Title.Trim());c.Parameters.AddWithValue(x.Body??"");c.Parameters.AddWithValue(x.Status);return await c.ExecuteNonQueryAsync()==0?Results.NotFound():Results.NoContent();});
app.MapDelete("/internal/admin/posts/{id:guid}",async(Guid id,HttpRequest req,NpgsqlDataSource db)=>{if(!Admin(req,out var user))return Results.NotFound();await using var c=db.CreateCommand("UPDATE content.posts SET status='archived',updated_at=now() WHERE id=$1 AND author_user_id=$2");c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(user);return await c.ExecuteNonQueryAsync()==0?Results.NotFound():Results.NoContent();});
app.Run();
static bool Admin(HttpRequest r,out Guid id)=>Guid.TryParse(r.HttpContext.User.FindFirst(JwtRegisteredClaimNames.Sub)?.Value,out id)&&r.HttpContext.User.IsInRole("admin");
record PostWrite(string Slug,string Title,string? Body,string Status);
