using System.IdentityModel.Tokens.Jwt;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Authorization;
using Npgsql;

var builder=WebApplication.CreateBuilder(args);
builder.Services.AddSingleton(_=>NpgsqlDataSource.Create(builder.Configuration.GetConnectionString("PriceAlert")??"Host=localhost;Port=5433;Database=trade_diary;Username=trade_diary;Password=local_only"));
builder.Services.AddAuthentication(JwtBearerDefaults.AuthenticationScheme).AddJwtBearer(o=>{o.MapInboundClaims=false;o.MetadataAddress=builder.Configuration["Auth:MetadataAddress"]??"http://127.0.0.1:5100/.well-known/openid-configuration";o.RequireHttpsMetadata=false;o.Audience="trade-diary-services";});
builder.Services.AddAuthorization(o=>o.FallbackPolicy=new AuthorizationPolicyBuilder().RequireAuthenticatedUser().Build());
var app=builder.Build();app.UseAuthentication();app.UseAuthorization();
app.MapGet("/health/live",()=>Results.Ok(new { status="healthy" })).AllowAnonymous();
app.MapGet("/health/ready",async(NpgsqlDataSource db)=>{try{await db.OpenConnectionAsync();return Results.Ok(new { status="ready" });}catch{return Results.Json(new { status="not_ready" },statusCode:503);}}).AllowAnonymous();
app.MapGet("/version",()=>Results.Ok(new { service="price-alert-service",version="0.1.0",marketContract="v1" })).AllowAnonymous();

app.MapGet("/internal/price-alerts",async(HttpRequest request,NpgsqlDataSource db)=>{if(!UserId(request,out var user))return Results.Unauthorized();await using var cmd=db.CreateCommand("SELECT id,symbol,condition_type,threshold,lookback_days,direction,status,baseline_close,last_evaluated_date,created_at,updated_at FROM price_alert.alerts WHERE user_id=$1 ORDER BY created_at DESC");cmd.Parameters.AddWithValue(user);await using var r=await cmd.ExecuteReaderAsync();var items=new List<AlertResponse>();while(await r.ReadAsync())items.Add(Read(r));return Results.Ok(new { items });});
app.MapPost("/internal/price-alerts",async(AlertWrite input,HttpRequest request,NpgsqlDataSource db)=>
{
    if(!UserId(request,out var user))return Results.Unauthorized();var error=Validate(input);if(error is not null)return Results.BadRequest(new { error });
    var symbol=input.Symbol.Trim().ToUpperInvariant();await using var connection=await db.OpenConnectionAsync();
    if(!await MarketHealthy(connection))return Results.Json(new { error="market_unhealthy" },statusCode:503);
    var latest=await LatestClose(connection,symbol);if(latest is null)return Results.BadRequest(new { error="symbol_has_no_published_price" });
    var id=Guid.NewGuid();await using var cmd=new NpgsqlCommand("INSERT INTO price_alert.alerts(id,user_id,symbol,condition_type,threshold,lookback_days,direction,status,baseline_close) VALUES($1,$2,$3,$4,$5,$6,$7,'active',$8) RETURNING id,symbol,condition_type,threshold,lookback_days,direction,status,baseline_close,last_evaluated_date,created_at,updated_at",connection);Add(cmd,id,user,symbol,input,input.ConditionType=="percent_change"?latest.Value.Close:null);await using var r=await cmd.ExecuteReaderAsync();await r.ReadAsync();return Results.Created($"/internal/price-alerts/{id}",Read(r));
});
app.MapPut("/internal/price-alerts/{id:guid}",async(Guid id,AlertWrite input,HttpRequest request,NpgsqlDataSource db)=>
{
    if(!UserId(request,out var user))return Results.Unauthorized();var error=Validate(input);if(error is not null)return Results.BadRequest(new { error });var symbol=input.Symbol.Trim().ToUpperInvariant();await using var connection=await db.OpenConnectionAsync();if(!await MarketHealthy(connection))return Results.Json(new { error="market_unhealthy" },statusCode:503);var latest=await LatestClose(connection,symbol);if(latest is null)return Results.BadRequest(new { error="symbol_has_no_published_price" });
    await using var cmd=new NpgsqlCommand("UPDATE price_alert.alerts SET symbol=$3,condition_type=$4,threshold=$5,lookback_days=$6,direction=$7,status='active',baseline_close=$8,last_evaluated_date=NULL,updated_at=now() WHERE id=$1 AND user_id=$2",connection);Add(cmd,id,user,symbol,input,input.ConditionType=="percent_change"?latest.Value.Close:null);return await cmd.ExecuteNonQueryAsync()==0?Results.NotFound():Results.NoContent();
});
app.MapDelete("/internal/price-alerts/{id:guid}",async(Guid id,HttpRequest request,NpgsqlDataSource db)=>{if(!UserId(request,out var user))return Results.Unauthorized();await using var cmd=db.CreateCommand("DELETE FROM price_alert.alerts WHERE id=$1 AND user_id=$2");cmd.Parameters.AddWithValue(id);cmd.Parameters.AddWithValue(user);return await cmd.ExecuteNonQueryAsync()==0?Results.NotFound():Results.NoContent();});
app.MapPost("/internal/price-alerts/{id:guid}/dismiss",async(Guid id,HttpRequest request,NpgsqlDataSource db)=>await SetStatus(id,"dismissed",request,db,false));
app.MapPost("/internal/price-alerts/{id:guid}/reactivate",async(Guid id,HttpRequest request,NpgsqlDataSource db)=>await SetStatus(id,"active",request,db,true));
app.MapGet("/internal/price-alerts/{id:guid}/triggers",async(Guid id,HttpRequest request,NpgsqlDataSource db)=>{if(!UserId(request,out var user))return Results.Unauthorized();await using var exists=db.CreateCommand("SELECT 1 FROM price_alert.alerts WHERE id=$1 AND user_id=$2");exists.Parameters.AddWithValue(id);exists.Parameters.AddWithValue(user);if(await exists.ExecuteScalarAsync() is null)return Results.NotFound();await using var cmd=db.CreateCommand("SELECT id,trading_date,observed_close,triggered_at,dismissed_at FROM price_alert.triggers WHERE alert_id=$1 ORDER BY triggered_at DESC");cmd.Parameters.AddWithValue(id);await using var r=await cmd.ExecuteReaderAsync();var items=new List<object>();while(await r.ReadAsync())items.Add(new { id=r.GetGuid(0),tradingDate=r.GetFieldValue<DateOnly>(1),observedClose=r.GetDecimal(2),triggeredAt=r.GetDateTime(3),dismissedAt=r.IsDBNull(4)?null:(DateTime?)r.GetDateTime(4) });return Results.Ok(new { items });});
app.MapPost("/internal/worker/run",async(NpgsqlDataSource db)=>Results.Ok(new { triggered=await Evaluate(db,100) }));
app.Run();

static bool UserId(HttpRequest r,out Guid id)=>Guid.TryParse(r.HttpContext.User.FindFirst(JwtRegisteredClaimNames.Sub)?.Value,out id);
static string? Validate(AlertWrite x){if(string.IsNullOrWhiteSpace(x.Symbol)||x.Symbol.Trim().Length>24)return "invalid_symbol";if(x.ConditionType is not ("above" or "below" or "percent_change" or "ma_crossing"))return "invalid_condition_type";if(x.ConditionType is "above" or "below" && x.Threshold<0)return "invalid_threshold";if(x.ConditionType=="percent_change"&&x.Threshold==0)return "invalid_threshold";if(x.ConditionType=="ma_crossing"&&(x.LookbackDays is <2 or >250||x.Direction is not ("above" or "below")))return "invalid_moving_average";return null;}
static void Add(NpgsqlCommand c,Guid id,Guid user,string symbol,AlertWrite x,decimal? baseline){c.Parameters.AddWithValue(id);c.Parameters.AddWithValue(user);c.Parameters.AddWithValue(symbol);c.Parameters.AddWithValue(x.ConditionType);c.Parameters.AddWithValue(x.Threshold);c.Parameters.AddWithValue((object?)x.LookbackDays??DBNull.Value);c.Parameters.AddWithValue((object?)x.Direction??DBNull.Value);c.Parameters.AddWithValue((object?)baseline??DBNull.Value);}
static AlertResponse Read(NpgsqlDataReader r)=>new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetDecimal(3),r.IsDBNull(4)?null:r.GetInt32(4),r.IsDBNull(5)?null:r.GetString(5),r.GetString(6),r.IsDBNull(7)?null:r.GetDecimal(7),r.IsDBNull(8)?null:r.GetFieldValue<DateOnly>(8),r.GetDateTime(9),r.GetDateTime(10));
static async Task<bool> MarketHealthy(NpgsqlConnection c){await using var cmd=new NpgsqlCommand("SELECT coalesce(bool_and(healthy),false) AND count(*)>0 FROM market.published_provider_health_v1",c);return (bool)(await cmd.ExecuteScalarAsync()??false);}
static async Task<(DateOnly Date,decimal Close)?> LatestClose(NpgsqlConnection c,string symbol){await using var cmd=new NpgsqlCommand("SELECT trade_date,adjusted_close FROM market_data_public.adjusted_daily_bars_v1 WHERE symbol=$1 ORDER BY trade_date DESC LIMIT 1",c);cmd.Parameters.AddWithValue(symbol);await using var r=await cmd.ExecuteReaderAsync();return await r.ReadAsync()?(r.GetFieldValue<DateOnly>(0),r.GetDecimal(1)):null;}
static async Task<IResult> SetStatus(Guid id,string status,HttpRequest request,NpgsqlDataSource db,bool requireHealthy){if(!UserId(request,out var user))return Results.Unauthorized();await using var connection=await db.OpenConnectionAsync();if(requireHealthy&&!await MarketHealthy(connection))return Results.Json(new { error="market_unhealthy" },statusCode:503);await using var cmd=new NpgsqlCommand("UPDATE price_alert.alerts SET status=$3,last_evaluated_date=CASE WHEN $3='active' THEN NULL ELSE last_evaluated_date END,updated_at=now() WHERE id=$1 AND user_id=$2",connection);cmd.Parameters.AddWithValue(id);cmd.Parameters.AddWithValue(user);cmd.Parameters.AddWithValue(status);return await cmd.ExecuteNonQueryAsync()==0?Results.NotFound():Results.NoContent();}
static async Task<int> Evaluate(NpgsqlDataSource db,int limit)
{
    await using var c=await db.OpenConnectionAsync();if(!await MarketHealthy(c))return 0;await using var tx=await c.BeginTransactionAsync();await using var claim=new NpgsqlCommand("SELECT id,symbol,condition_type,threshold,lookback_days,direction,baseline_close FROM price_alert.alerts WHERE status='active' ORDER BY created_at FOR UPDATE SKIP LOCKED LIMIT $1",c,tx);claim.Parameters.AddWithValue(limit);var alerts=new List<Due>();await using(var r=await claim.ExecuteReaderAsync())while(await r.ReadAsync())alerts.Add(new(r.GetGuid(0),r.GetString(1),r.GetString(2),r.GetDecimal(3),r.IsDBNull(4)?null:r.GetInt32(4),r.IsDBNull(5)?null:r.GetString(5),r.IsDBNull(6)?null:r.GetDecimal(6)));
    var count=0;foreach(var a in alerts){var bars=await Bars(c,tx,a.Symbol,a.Lookback??2);if(bars.Count==0)continue;var latest=bars[0];var hit=a.Type switch{"above"=>latest.Close>=a.Threshold,"below"=>latest.Close<=a.Threshold,"percent_change"=>a.Baseline is not null&&(latest.Close-a.Baseline.Value)/a.Baseline.Value*100m*(a.Threshold<0?-1:1)>=Math.Abs(a.Threshold),"ma_crossing"=>Crossed(bars,a.Lookback!.Value,a.Direction!),_=>false};await using var update=new NpgsqlCommand("UPDATE price_alert.alerts SET last_evaluated_date=$2,updated_at=now() WHERE id=$1",c,tx);update.Parameters.AddWithValue(a.Id);update.Parameters.AddWithValue(latest.Date);await update.ExecuteNonQueryAsync();if(!hit)continue;await using var insert=new NpgsqlCommand("INSERT INTO price_alert.triggers(id,alert_id,trading_date,observed_close) VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING",c,tx);insert.Parameters.AddWithValue(Guid.NewGuid());insert.Parameters.AddWithValue(a.Id);insert.Parameters.AddWithValue(latest.Date);insert.Parameters.AddWithValue(latest.Close);if(await insert.ExecuteNonQueryAsync()==0)continue;await using var state=new NpgsqlCommand("UPDATE price_alert.alerts SET status='triggered',updated_at=now() WHERE id=$1",c,tx);state.Parameters.AddWithValue(a.Id);await state.ExecuteNonQueryAsync();count++;}await tx.CommitAsync();return count;
}
static async Task<List<Bar>> Bars(NpgsqlConnection c,NpgsqlTransaction tx,string symbol,int lookback){await using var cmd=new NpgsqlCommand("SELECT trade_date,adjusted_close FROM market_data_public.adjusted_daily_bars_v1 WHERE symbol=$1 ORDER BY trade_date DESC LIMIT $2",c,tx);cmd.Parameters.AddWithValue(symbol);cmd.Parameters.AddWithValue(lookback+1);await using var r=await cmd.ExecuteReaderAsync();var bars=new List<Bar>();while(await r.ReadAsync())bars.Add(new(r.GetFieldValue<DateOnly>(0),r.GetDecimal(1)));return bars;}
static bool Crossed(List<Bar> bars,int n,string direction){if(bars.Count<n+1)return false;var current=bars.Take(n).Average(x=>x.Close);var previous=bars.Skip(1).Take(n).Average(x=>x.Close);return direction=="above"?bars[0].Close>=current&&bars[1].Close<previous:bars[0].Close<=current&&bars[1].Close>previous;}
record AlertWrite(string Symbol,string ConditionType,decimal Threshold,int? LookbackDays,string? Direction);
record AlertResponse(Guid Id,string Symbol,string ConditionType,decimal Threshold,int? LookbackDays,string? Direction,string Status,decimal? BaselineClose,DateOnly? LastEvaluatedDate,DateTime CreatedAt,DateTime UpdatedAt);
record Due(Guid Id,string Symbol,string Type,decimal Threshold,int? Lookback,string? Direction,decimal? Baseline);
record Bar(DateOnly Date,decimal Close);
