import { useEffect, useState } from 'react'
import type { FormEvent, ReactNode } from 'react'
import * as api from './api'
import type { Alert, Calendar, Diary, Discipline, Transaction } from './api'
import './App.css'

type Page = 'Today' | 'Diary' | 'Calendar' | 'Discipline' | 'Alerts'
const pages: Page[] = ['Today', 'Diary', 'Calendar', 'Discipline', 'Alerts']
const today = () => new Date().toLocaleDateString('en-CA')

function Login({ onDone }: { onDone: () => void }) {
  const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState('')
  async function submit(e:FormEvent){e.preventDefault();setError('');try{await api.login(email,password);onDone()}catch{setError('Email or password is incorrect.')}}
  return <main className="login-page"><form className="card login" onSubmit={submit}><Brand/><small>WELCOME BACK</small><h1>Your decisions, remembered.</h1><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required/></label>{error&&<p role="alert" className="error">{error}</p>}<button className="primary">Sign in</button></form></main>
}
const Brand=()=> <div className="brand"><span>m</span> micro cockpit</div>
function AsyncState({loading,error,empty,children}:{loading:boolean;error:string;empty?:boolean;children:ReactNode}) { if(loading)return <p className="empty">Loading…</p>;if(error)return <p className="error" role="alert">{error}</p>;if(empty)return <p className="empty">Nothing here yet.</p>;return <>{children}</> }

function TodayPage({go}:{go:(p:Page)=>void}) {
 const [data,setData]=useState<api.Dashboard|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState(''),[note,setNote]=useState(''),[message,setMessage]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setData(await api.getDashboard())}catch{setError('Dashboard is unavailable.')}finally{setLoading(false)}}
 useEffect(()=>{void load()},[])
 async function save(){if(!note.trim()||!data)return;try{await api.saveQuickNote(data.localDate,note.trim());setNote('');setMessage('Saved.');await load()}catch{setMessage('Could not save.')}}
 return <AsyncState loading={loading} error={error}>{data&&<><PageHeader eyebrow={data.localDate} title="Good evening"/><section className="quick card"><label>What did you notice?</label><textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="A thought, signal, or decision…"/><div><span>{message||'Quick note'}</span><button className="primary" onClick={save}>Save note</button></div></section><section className="grid"><article className="card action"><small>TODAY'S DIARY</small><h2>{data.diary.writtenToday?'You showed up today.':'Make the day memorable.'}</h2><p>{data.diary.count} entries.</p><button onClick={()=>go('Diary')}>Open diary →</button></article><article className="card pnl"><small>DAILY P/L</small><strong>{data.performance?.pnlAmount.toLocaleString()??'—'}</strong><p>{data.performance?.pnlPercent==null?'No result recorded':`${data.performance.pnlPercent.toFixed(2)}%`}</p><button onClick={()=>go('Calendar')}>Open calendar</button></article><article className="card discipline"><small>TODAY'S DISCIPLINE</small><blockquote>“{data.discipline?.content??'Add a principle.'}”</blockquote><button onClick={()=>go('Discipline')}>Manage principles</button></article></section></>}</AsyncState>
}

function DiaryPage(){
 const [items,setItems]=useState<Diary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[title,setTitle]=useState(''),[content,setContent]=useState(''),[date,setDate]=useState(today()),[editing,setEditing]=useState<Diary|null>(null),[trading,setTrading]=useState<string|null>(null)
 const load=async()=>{setLoading(true);setError('');try{setItems((await api.getDiaries()).items)}catch{setError('Could not load diaries.')}finally{setLoading(false)}};useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();try{if(editing)await api.updateDiary(editing.id,date,title,content);else await api.createDiary(date,title,content);setTitle('');setContent('');setEditing(null);await load()}catch{setError('Could not save diary.')}}
 const edit=(d:Diary)=>{setEditing(d);setTitle(d.title);setContent(d.content);setDate(d.localDate);scrollTo({top:0,behavior:'smooth'})}
 return <><PageHeader eyebrow="JOURNAL" title="Diary"/><form className="card form" onSubmit={submit}><div className="form-row"><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label><label>Title<input value={title} onChange={e=>setTitle(e.target.value)} required maxLength={160}/></label></div><label>Reflection<textarea value={content} onChange={e=>setContent(e.target.value)} placeholder="What happened, and what will you remember?"/></label><div className="form-actions">{editing&&<button type="button" onClick={()=>{setEditing(null);setTitle('');setContent('')}}>Cancel</button>}<button className="primary">{editing?'Update':'Create'} diary</button></div></form><section className="stack"><AsyncState loading={loading} error={error} empty={!items.length}>{items.map(d=><article className="card diary-item" key={d.id}><div className="item"><div><small>{d.localDate}</small><h2>{d.title}</h2><p className="prewrap">{d.content||'No reflection added.'}</p></div><div className="item-actions"><button onClick={()=>setTrading(trading===d.id?null:d.id)}>Trades</button><button onClick={()=>edit(d)}>Edit</button><button className="danger" onClick={async()=>{if(confirm('Delete this diary?')){await api.deleteDiary(d.id);await load()}}}>Delete</button></div></div>{trading===d.id&&<TransactionPanel diaryId={d.id}/>}</article>)}</AsyncState></section></>
}

function TransactionPanel({diaryId}:{diaryId:string}){
 const [items,setItems]=useState<Transaction[]>([]),[error,setError]=useState(''),[symbol,setSymbol]=useState(''),[side,setSide]=useState('buy'),[quantity,setQuantity]=useState(''),[price,setPrice]=useState(''),[currency,setCurrency]=useState('USD'),[tradedAt,setTradedAt]=useState(new Date().toISOString().slice(0,16)),[notes,setNotes]=useState('')
 const load=async()=>{try{setItems((await api.getTransactions(diaryId)).items)}catch{setError('Could not load trades.')}};useEffect(()=>{void load()},[diaryId])
 async function submit(e:FormEvent){e.preventDefault();setError('');try{await api.createTransaction(diaryId,{symbol,side,quantity:Number(quantity),price:Number(price),currency,tradedAt:new Date(tradedAt).toISOString(),notes});setSymbol('');setQuantity('');setPrice('');setNotes('');await load()}catch{setError('Could not save trade.')}}
 return <div className="transactions"><h3>Transactions</h3><form className="trade-form" onSubmit={submit}><input aria-label="Symbol" placeholder="Symbol" value={symbol} onChange={e=>setSymbol(e.target.value)} required/><select aria-label="Side" value={side} onChange={e=>setSide(e.target.value)}><option value="buy">Buy</option><option value="sell">Sell</option></select><input aria-label="Quantity" type="number" min="0" step="any" placeholder="Quantity" value={quantity} onChange={e=>setQuantity(e.target.value)} required/><input aria-label="Price" type="number" min="0" step="any" placeholder="Price" value={price} onChange={e=>setPrice(e.target.value)} required/><input aria-label="Currency" value={currency} onChange={e=>setCurrency(e.target.value)} required/><input aria-label="Traded at" type="datetime-local" value={tradedAt} onChange={e=>setTradedAt(e.target.value)} required/><input aria-label="Notes" placeholder="Notes" value={notes} onChange={e=>setNotes(e.target.value)}/><button className="primary">Add trade</button></form>{error&&<p className="error">{error}</p>}{items.length?<div className="trade-list">{items.map(t=><div key={t.id}><span><b>{t.side.toUpperCase()} {t.symbol}</b> · {t.quantity} × {t.price} {t.currency}</span><button className="danger" onClick={async()=>{await api.deleteTransaction(diaryId,t.id);await load()}}>Delete</button></div>)}</div>:<p className="empty">No transactions.</p>}</div>
}

function CalendarPage(){
 const now=new Date(),[cursor,setCursor]=useState(new Date(now.getFullYear(),now.getMonth(),1)),[data,setData]=useState<Calendar|null>(null),[selected,setSelected]=useState(today()),[loading,setLoading]=useState(true),[error,setError]=useState(''),[amount,setAmount]=useState(''),[capital,setCapital]=useState(''),[note,setNote]=useState('')
 const load=async()=>{setLoading(true);setError('');try{setData(await api.getCalendar(cursor.getFullYear(),cursor.getMonth()+1))}catch{setError('Could not load calendar.')}finally{setLoading(false)}};useEffect(()=>{void load()},[cursor])
 const day=data?.days.find(x=>x.date===selected);useEffect(()=>{setAmount(day?.performance?.pnlAmount?.toString()??'');setNote(day?.performance?.note??'')},[day?.date,day?.performance?.pnlAmount])
 async function save(e:FormEvent){e.preventDefault();try{await api.savePerformance(selected,Number(amount),capital?Number(capital):null,note);await load()}catch{setError('Could not save P/L.')}}
 const first=data?new Date(data.year,data.month-1,1).getDay():0
 return <><PageHeader eyebrow="PERFORMANCE" title="Calendar"/><div className="calendar-head"><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()-1,1))}>←</button><h2>{cursor.toLocaleDateString(undefined,{month:'long',year:'numeric'})}</h2><button onClick={()=>setCursor(new Date(cursor.getFullYear(),cursor.getMonth()+1,1))}>→</button></div><AsyncState loading={loading} error={error}>{data&&<><section className="calendar card"><div className="weekdays">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(x=><small key={x}>{x}</small>)}</div><div className="days">{Array.from({length:first},(_,i)=><span key={`blank${i}`}/>) }{data.days.map(d=><button key={d.date} className={`${selected===d.date?'selected ':''}${(d.performance?.pnlAmount??0)>0?'gain':(d.performance?.pnlAmount??0)<0?'loss':''}`} onClick={()=>setSelected(d.date)}><b>{Number(d.date.slice(-2))}</b><span>{d.performance?d.performance.pnlAmount.toLocaleString():'·'}</span>{d.diaryCount>0&&<i>{d.diaryCount} note{d.diaryCount>1?'s':''}</i>}</button>)}</div></section><form className="card form pnl-form" onSubmit={save}><h2>{selected} P/L</h2><div className="form-row"><label>P/L amount<input type="number" step="any" value={amount} onChange={e=>setAmount(e.target.value)} required/></label><label>Capital base (optional)<input type="number" min="0" step="any" value={capital} onChange={e=>setCapital(e.target.value)}/></label></div><label>Note<input value={note} onChange={e=>setNote(e.target.value)}/></label><div className="form-actions"><button className="primary">Save P/L</button></div></form></>}</AsyncState></>
}

function DisciplinePage(){
 const [items,setItems]=useState<Discipline[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[content,setContent]=useState('');const load=async()=>{setLoading(true);setError('');try{setItems((await api.getDisciplines()).items)}catch{setError('Could not load disciplines.')}finally{setLoading(false)}};useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();try{await api.createDiscipline(content);setContent('');await load()}catch{setError('Could not add principle.')}}
 return <><PageHeader eyebrow="PROCESS" title="Discipline"/><form className="card inline-form" onSubmit={submit}><input value={content} onChange={e=>setContent(e.target.value)} placeholder="A principle worth remembering" required/><button className="primary">Add</button></form><section className="stack"><AsyncState loading={loading} error={error} empty={!items.length}>{items.map((d,i)=><article className="card item" key={d.id}><div><small>PRINCIPLE {i+1}</small><blockquote>“{d.content}”</blockquote></div><button className="danger" onClick={async()=>{await api.deleteDiscipline(d.id);await load()}}>Delete</button></article>)}</AsyncState></section></>
}

function AlertsPage(){
 const [alerts,setAlerts]=useState<Alert[]>([]),[diaries,setDiaries]=useState<Diary[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(''),[diaryId,setDiaryId]=useState(''),[date,setDate]=useState(today()),[time,setTime]=useState('09:00'),[repeat,setRepeat]=useState('none');const timezone=Intl.DateTimeFormat().resolvedOptions().timeZone
 const load=async()=>{setLoading(true);setError('');try{const [a,d]=await Promise.all([api.getAlerts(),api.getDiaries()]);setAlerts(a.items);setDiaries(d.items);setDiaryId(x=>x||d.items[0]?.id||'')}catch{setError('Could not load alerts.')}finally{setLoading(false)}};useEffect(()=>{void load()},[])
 async function submit(e:FormEvent){e.preventDefault();try{await api.createAlert({diaryId,startLocalDate:date,localTime:time,timezone,repeatMode:repeat});await load()}catch{setError('Could not create alert.')}}
 return <><PageHeader eyebrow="REMINDERS" title="Diary alerts"/><form className="card form" onSubmit={submit}><div className="form-row"><label>Diary<select value={diaryId} onChange={e=>setDiaryId(e.target.value)} required><option value="">Choose a diary</option>{diaries.map(d=><option key={d.id} value={d.id}>{d.title}</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></label></div><div className="form-row"><label>Time<input type="time" value={time} onChange={e=>setTime(e.target.value)} required/></label><label>Repeat<select value={repeat} onChange={e=>setRepeat(e.target.value)}><option value="none">None</option><option value="week">Weekdays this week</option><option value="month">Weekdays this month</option></select></label></div><div className="form-actions"><button className="primary" disabled={!diaries.length}>Create alert</button></div>{!diaries.length&&!loading&&<p>Create a diary first.</p>}</form><section className="stack"><AsyncState loading={loading} error={error} empty={!alerts.length}>{alerts.map(a=><article className="card item" key={a.id}><div><small>{a.status.toUpperCase()}</small><h2>{diaries.find(d=>d.id===a.diaryId)?.title??'Diary reminder'}</h2><p>{a.nextLocalDate??a.startLocalDate} at {a.localTime.slice(0,5)} · {a.repeatMode}</p></div><div className="item-actions">{a.status==='active'&&<button onClick={async()=>{await api.dismissAlert(a.id);await load()}}>Dismiss</button>}<button className="danger" onClick={async()=>{await api.deleteAlert(a.id);await load()}}>Delete</button></div></article>)}</AsyncState></section></>
}

const PageHeader=({eyebrow,title}:{eyebrow:string;title:string})=><header><div><small>{eyebrow}</small><h1>{title}</h1></div><button className="avatar" title="Sign out" onClick={()=>{localStorage.removeItem('accessToken');location.reload()}}>KL</button></header>
function App(){const [authenticated,setAuthenticated]=useState(Boolean(localStorage.getItem('accessToken'))),[page,setPage]=useState<Page>('Today');if(!authenticated)return <Login onDone={()=>setAuthenticated(true)}/>;const content={Today:<TodayPage go={setPage}/>,Diary:<DiaryPage/>,Calendar:<CalendarPage/>,Discipline:<DisciplinePage/>,Alerts:<AlertsPage/>}[page];return <div className="shell"><aside><Brand/><nav>{pages.map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}</nav></aside><main>{content}</main><nav className="mobile-nav">{pages.map(p=><button key={p} className={page===p?'active':''} onClick={()=>setPage(p)}>{p}</button>)}</nav></div>}
export default App
